name: ow_api_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Data
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.12

  # Utils
  package_info: ^2.0.2
  equatable: ^2.0.3
  path_provider: ^2.0.8
  connectivity_plus: ^2.2.0
  intl: ^0.17.0
  google_fonts: ^2.2.0
  url_launcher: ^6.0.18

  # Networking
  http: ^0.13.4

  #BLoC
  flutter_bloc: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/heroIcons/
    - assets/platformIcon/
    - assets/rankIcons/
    - assets/roleIcons/