name: ow_api_app
description: A new Flutter project.

version: 0.5.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Data
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  shared_preferences: ^0.5.12

  # Utils
  package_info: ^2.0.0
  equatable: ^1.2.5
  path_provider: ^1.6.5
  connectivity: ^2.0.2
  intl: ^0.17.0
  google_fonts: ^1.1.2

  # Networking
  http: ^0.12.2

  #BLoC
  flutter_bloc: ^6.0.6

  # UI
  flutter_dropdown: ^0.0.8
  persistent_bottom_nav_bar: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.0
  hive_generator: ^0.7.3
  build_runner: ^1.10.1

flutter:
  assets:
    - assets/heroIcons/ana.png
    - assets/heroIcons/ashe.png
    - assets/heroIcons/baptiste.png
    - assets/heroIcons/bastion.png
    - assets/heroIcons/brigitte.png
    - assets/heroIcons/doomfist.png
    - assets/heroIcons/dva.png
    - assets/heroIcons/echo.png
    - assets/heroIcons/genji.png
    - assets/heroIcons/hanzo.png
    - assets/heroIcons/junkrat.png
    - assets/heroIcons/lucio.png
    - assets/heroIcons/mccree.png
    - assets/heroIcons/mei.png
    - assets/heroIcons/mercy.png
    - assets/heroIcons/moira.png
    - assets/heroIcons/orisa.png
    - assets/heroIcons/pharah.png
    - assets/heroIcons/reaper.png
    - assets/heroIcons/rein.png
    - assets/heroIcons/roadhog.png
    - assets/heroIcons/sigma.png
    - assets/heroIcons/soldier-76.png
    - assets/heroIcons/sombra.png
    - assets/heroIcons/symmetra.png
    - assets/heroIcons/torbjorn.png
    - assets/heroIcons/tracer.png
    - assets/heroIcons/widowmaker.png
    - assets/heroIcons/winston.png
    - assets/heroIcons/wrecking-ball.png
    - assets/heroIcons/zarya.png
    - assets/heroIcons/zenyatta.png

  uses-material-design: true



