name: ow_api_app
description: A new Flutter project.

version: 0.6.2

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Data
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  shared_preferences: ^2.0.6

  # Utils
  package_info: ^2.0.0
  equatable: ^1.2.5
  path_provider: ^2.0.2
  connectivity_plus: ^1.0.2
  intl: ^0.17.0
  google_fonts: ^1.1.2
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.6

  # Networking
  http: ^0.12.2

  #BLoC
  flutter_bloc: ^6.0.6

  # UI
  flutter_dropdown: ^0.0.8
  page_transition: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3
  hive_generator: ^1.1.0
  build_runner: ^1.10.1

flutter:
  assets:
    - assets/overwatch-logo.png
    - assets/roleIcons/icon-offense.png
    - assets/roleIcons/icon-support.png
    - assets/roleIcons/icon-tank.png
    - assets/heroIcons/ana.png
    - assets/heroIcons/ashe.png
    - assets/heroIcons/baptiste.png
    - assets/heroIcons/bastion.png
    - assets/heroIcons/brigitte.png
    - assets/heroIcons/doomfist.png
    - assets/heroIcons/dva.png
    - assets/heroIcons/echo.png
    - assets/heroIcons/genji.png
    - assets/heroIcons/hanzo.png
    - assets/heroIcons/junkrat.png
    - assets/heroIcons/lucio.png
    - assets/heroIcons/mccree.png
    - assets/heroIcons/mei.png
    - assets/heroIcons/mercy.png
    - assets/heroIcons/moira.png
    - assets/heroIcons/orisa.png
    - assets/heroIcons/pharah.png
    - assets/heroIcons/reaper.png
    - assets/heroIcons/rein.png
    - assets/heroIcons/roadhog.png
    - assets/heroIcons/sigma.png
    - assets/heroIcons/soldier-76.png
    - assets/heroIcons/sombra.png
    - assets/heroIcons/symmetra.png
    - assets/heroIcons/torbjorn.png
    - assets/heroIcons/tracer.png
    - assets/heroIcons/widowmaker.png
    - assets/heroIcons/winston.png
    - assets/heroIcons/wrecking-ball.png
    - assets/heroIcons/zarya.png
    - assets/heroIcons/zenyatta.png

  uses-material-design: true



