name: ow_api_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Data
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.12

  # Utils
  package_info: ^2.0.2
  equatable: ^2.0.3
  path_provider: ^2.0.8
  connectivity_plus: ^2.2.0
  intl: ^0.17.0
  google_fonts: ^2.2.0
  url_launcher: ^6.0.18

  # Networking
  http: ^0.13.4

  #BLoC
  flutter_bloc: ^8.0.1

  # UI
  flutter_dropdown: ^1.0.0+hotfix.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  hive_generator: ^1.1.2
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4


flutter:
  uses-material-design: true
  assets:
    - assets/overwatch-logo.png
    - assets/platformIcon/xbox_icon.png
    - assets/platformIcon/playstation_icon.png
    - assets/platformIcon/nintendo_switch_icon.png
    - assets/platformIcon/battle_net_icon.png
    - assets/roleIcons/icon-damage.png
    - assets/roleIcons/icon-support.png
    - assets/roleIcons/icon-tank.png
    - assets/heroIcons/ana.png
    - assets/heroIcons/ashe.png
    - assets/heroIcons/baptiste.png
    - assets/heroIcons/bastion.png
    - assets/heroIcons/brigitte.png
    - assets/heroIcons/doomfist.png
    - assets/heroIcons/dva.png
    - assets/heroIcons/echo.png
    - assets/heroIcons/genji.png
    - assets/heroIcons/hanzo.png
    - assets/heroIcons/junkrat.png
    - assets/heroIcons/lucio.png
    - assets/heroIcons/mccree.png
    - assets/heroIcons/mei.png
    - assets/heroIcons/mercy.png
    - assets/heroIcons/moira.png
    - assets/heroIcons/orisa.png
    - assets/heroIcons/pharah.png
    - assets/heroIcons/reaper.png
    - assets/heroIcons/rein.png
    - assets/heroIcons/roadhog.png
    - assets/heroIcons/sigma.png
    - assets/heroIcons/soldier-76.png
    - assets/heroIcons/sombra.png
    - assets/heroIcons/symmetra.png
    - assets/heroIcons/torbjorn.png
    - assets/heroIcons/tracer.png
    - assets/heroIcons/widowmaker.png
    - assets/heroIcons/winston.png
    - assets/heroIcons/wrecking-ball.png
    - assets/heroIcons/zarya.png
    - assets/heroIcons/zenyatta.png