name: ow_api_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  equatable: ^1.2.5
  flutter_bloc: ^6.0.6
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  path_provider: ^1.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.5.0
  hive_generator: ^0.7.3
  build_runner: ^1.10.1

flutter:
  fonts:
    - family: TitilliumWeb
      fonts:
        - asset: fonts/TitilliumWeb-Black.ttf
        - asset: fonts/TitilliumWeb-Bold.ttf
        - asset: fonts/TitilliumWeb-BoldItalic.ttf
        - asset: fonts/TitilliumWeb-ExtraLight.ttf
        - asset: fonts/TitilliumWeb-ExtraLightItalic.ttf
        - asset: fonts/TitilliumWeb-Italic.ttf
        - asset: fonts/TitilliumWeb-Light.ttf
        - asset: fonts/TitilliumWeb-LightItalic.ttf
        - asset: fonts/TitilliumWeb-Regular.ttf
  uses-material-design: true



